### ISSUE TITLE
Support cross-platform install

### ISSUE THREAD

**Issue by ksangster** [equinor/eNLP#1]
## Description
_Describe the motivation for this issue_

Currently, the install is performed via 
```
make install
```
This works on Linux. Windows systems by default do not have ```make``` installed.  Update or add script(s) that enable Windows users to use ```pip``` for installation.

## Background Information
_Any information useful to the assignee_

Installation steps can be found: ```./Makefile```. This file calls pip to run various versions of the installation.

## Tasks
_List individual tasks to be completed_
- [x] _a: Verfiy manual install on Windows
- [x] _b: Build docs
- [x] _c: Run tests
- [x] _d: Import the library and run manually

## Definition of Done
_On which condition can this ticket be closed?_

Since all users in the Equinor environment should have pip installed by default, installation should be performed running:
```
pip install enlp
```
or something similar.

**Comment by ksangster** [comment]
The manual way to install on Windows:

- Clone the repo:
``` git clone https://github.com/equinor/eNLP.git```
by default, this will unpack into a new ```eNLP``` subdirectory.

- Define and activate your Python virtual environment:
``` python -m venv <your_venv>```
and activate it:
``` <your_venv>\Scripts\activate```

- With your virtual environment activated, navigate to where you cloned the repo. Run the following:
```path\to\repo>> <your_venv>\Scripts\pip.exe install -r requirements.txt```
```path\to\repo>> <your_venv>\Scripts\pip.exe install .```

The first line will install all the libraries and dependencies. The second line will install the eNLP module itself.

To check the installation, start the Python interactive prompt:
```python```
at the ```>>>``` prompt, type:
```import enlp```
Installation succeeded if you see only ```>>>``` again.

**Comment by cebirnie92** [comment]
I don't fully understand the issue as the Makefile is only advisory, and as you point out the commands and files are there so it is just to use the pip commands manually. Would you recommend an updating of the README to help users with installation on windows?

**Comment by cebirnie92** [comment]
The package is due to be opensourced and when that happens it shall be available by `pip install` so perhaps that would resolve this issue without updating the readme.

**Comment by ksangster** [comment]
> I don't fully understand the issue as the Makefile is only advisory, and as you point out the commands and files are there so it is just to use the pip commands manually. Would you recommend an updating of the README to help users with installation on windows?

The issue, as I understood it, is other users want to use the package, but on Windows. Following the steps in the README on Windows doesn't work because ```make``` isn't installed by default. 


> The package is due to be opensourced and when that happens it shall be available by `pip install` so perhaps that would resolve this issue without updating the readme.

Yes, that would resolve the issue. And in the meantime, the README can be updated to reflect the steps needed for Windows installation.

**Comment by cebirnie92** [comment]
Okay, in the case that a Windows user wants to contribute back to the package or wants to use the package before its on PyPi then I think it would be good the README covers windows installation as well. I will update it shortly.

**Comment by cebirnie92** [comment]
Related note: CI build on DevOps now in place that tests Windows build and tests.
